### ISSUE TITLE
AmazModService has stopped

### ISSUE THREAD

**Issue by carstengrimm** [edotassi/AmazMod#110]
I just installed the play store app (to phone) as well as the service apk (to watch)
and disabled notifications in amazfit application.

running amazmod application it shows watch's information and so on.

when receiving a notification - in this case email via k-9 mail it shows "amazmodservice has stopped" prompting some "arrow / check" button. a notification is still shown but the error will be repeated all the time after each notification coming in.

Running  AmazFit 2 / AmazFit STRATOS | rel 13 | 2.0.29.0

**Comment by lfom** [comment]
@carstengrimm Does it happen only with K-9? Is it possible to provide a logcat from watch when the error happens (filter by "amazmod")? Thank you.

**Comment by carstengrimm** [comment]
i updated to a newer OS Version 2.0.32.0 and it seems like that (partly?) fixed it.

**Comment by lfom** [comment]
@carstengrimm  Weird, if you can share a logcat it will help tracking the problem anyway. Thanks for reporting back.

**Comment by gyrdym** [comment]
Guys, I also got this error, but in case of incoming call notification. It always happens when the app is connected to my watch and I receive incoming call. After that, apparently, the service (which I have installed on the watch via provided .apk file) stops permanently, until my watch gets rebooted.

**Comment by lfom** [comment]
@gyrdym Please make sure:
- You have uninstalled old versions of AmazMod and you have the latest stock version of Amazfit installed on phone with push notifications disable;
- Do not enable notification for the callu/telephone app in AmazMod, call notifications are handled by AmazFit, if you want notifications for missed calls, then probably it's another app like Contacts, etc.

if you still have crashes, please provide logcats with "amazmod" as filter or it will be almost impossible to debug the crash.

**Comment by gyrdym** [comment]
@lfom It works. The cause was callui notification. I switched it off and everything became good. Thank you!

**Comment by gyrdym** [comment]
@lfom but, is there a way to make this more obvious? E.g. some kind of warning in the application when one tries to switch on callui/phone notification.

**Comment by gyrdym** [comment]
@lfom you have a point here, but first thing that I did as I installed the app, I switch on all notifications that I need, because I disabled push notifications on the stock app. Incoming call is the most important notification for me, so I strived to find it and I found one :) I thought, if I have disabled all the notifications in the stock app, I should enable them on your app. Now I totally understand all, thank you for clarification, but, I think, there will be some people like me, that face this problem like I

**Comment by lfom** [comment]
Info added to FAQ.
