### ISSUE TITLE
Need a simple way to close notification message

### ISSUE THREAD

**Issue by EgorOA** [edotassi/AmazMod#140]
The feature request for swipe out to close notification was rejected (https://github.com/edotassi/AmazMod/issues/132)
But I insist that must be a simple way to close notification message rather that scroll down a few screens, find the close button and aim it.
If u dont want make a swipe mechanism, u can add close button on the upper right side for example.
Think about usability, please!

**Comment by lfom** [comment]
As I said, swipe isn't available right now, it would break other stuff. I don't have any problem scrolling to close as it is always the last button, hard to miss. But if some people find it so hard to tap a button, maybe adding a floating "x" that would close the activity is possible?

**Comment by edotassi** [comment]
swipe is disabled in this method: 
https://github.com/edotassi/AmazMod/blob/71748d42182b49f29781c1e487e12dce8dc12f17/service/src/main/java/com/amazmod/service/ui/NotificationActivity.java#L195

it was disabled because add a black layer behind activity

maybe we should add a preference to enable/disable

**Comment by lfom** [comment]
I have tried disabling it in the past so we could use swipe left to show more options, but then scrolling to read the message or to reach replies was terrible...

**Comment by GrinFactor** [comment]
Usage scenario... you're running and receive a notification but you want to get rid of it as soon as possible because you want to see your watchface or activity etc. A quick way to exit the custom way would be really useful. I agree with EgorOA. If it is at all possible the swiping option would be great.

**Comment by EgorOA** [comment]
Keep in mind that watch interface means sweep right as "Escape" or "Cancel". So don't reinvent the wheel...

**Comment by lfom** [comment]
![ss01](https://user-images.githubusercontent.com/15659999/44489175-1de5ae00-a631-11e8-83a5-acfd0d172c04.png)

**Comment by edotassi** [comment]
can be closed?

**Comment by EgorOA** [comment]
Good work.
But I still can't understand  why swipe functionality was rejected? Swipe right - close, swype left - reply?
And one more thing: close button is in the bottom of message, if message is long you have to scroll a lot to get to the close button :(

**Comment by lfom** [comment]
Closing it... Activity can't be swiped away as explained, this will be changed in the future, probably.

**Comment by dimov-cz** [comment]
Any updates on this?
