### ISSUE TITLE
The notification menu layout adjustment.

### ISSUE THREAD

**Issue by mania3416** [edotassi/AmazMod#177]
The notification menu layout adjustment.

1. Maybe I'm wrong, but the app icon's resolution seems not sharp enough.

2. The app icon is too hight, it almost touches the edge of the screen.

3. The actual content of the notification is too far away from the date/time and quick reply button (those vacancies on the top and bottom of content is too large).

4. Can all the notification from amazmod can be listing and synchronize with the phone (when it been cleared from the phone it will disappear unless it will keep showing on the log list) like the official notification log?

**Comment by lfom** [comment]
1. Replies shows a black & white low resolution icon, it's by design to save data/battery and how notifications on android work
2. It's as high as it can be to save space for content
3. Margin/padding has been improved as 1.0.49 release
4. "StandardUI" notifications are saved on watch, just like what happens with Amazfit (so no replies, of course)
