### ISSUE TITLE
Constantly resetting brightness in the Tweaking section

### ISSUE THREAD

**Issue by artemonic** [edotassi/AmazMod#185]
I'm setting the brightness in the Tweaking section and, as soon as I go out from it, it resets to zero (I can see it if I go back in to Tweaking).
For some time the watch is remain with the brightness setting I gave before reset, but after a while (hour or more) it drops to zero. Looks like it updates to reseted value from the phone app.

**Comment by GreatApo** [comment]
@rastaboo the brightness value you select is directly transferred to your watch without been saved in settings (this happens in order to avoid requesting data from the watch). That is why if you go back and then in, it is 0.

Additionally, brightness data are send only if you move the bar thus the brightness if not changed because of the tweak section.

Do you have "disable screen on" turned on in settings? That feature messes with watch's brightness and may be a little buggy...
